book:
  name: "Java"
spring:
  config:
    import: "classpath:my-dev.yml"
  #import: optional:file:E:\\workspace\\springBoot-demo\\src\\main\\resources\\dev.properties
  profiles:
    active: dev
  app:
    name: "springboot-demo"
    descript: "${spring.app.name} is a springboot application"

  output:
    ansi:
      enabled: detect

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb1?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456


rand:
  number: ${random.value}
  intNumber: ${random.int}
  longNumber: ${random.long}
  uuid: ${random.uuid}


##debug: true
logging:
  file:
    name: my.log
